### ISSUE TITLE
Creating Smooth transition Between Two Animations Literature

### ISSUE THREAD

**Issue by sensible-heart** [CMPUT414/DancingQueen#6]
Will find at least two scholarly articles that examine creating smooth transitions between two different animations.

**Comment by kevindeasis** [comment]
When do you need this?

**Comment by vanbelle** [comment]
The presentation is in two - three weeks I think, so it would probably be good to have them by February 5th, then we can write up our presentation and make the slides in the week after. 

Sarah Van Belleghem

**Comment by kevindeasis** [comment]
Do you guys need a write up & summary? Or do you guys just want the articles around the 5th; including me being prepared for the presentation?

**Comment by vanbelle** [comment]
Just having the articles should be good for the fifth. We will do the write ups the week after. Though if you have time there's no reason not to do write ups early.

**Comment by kevindeasis** [comment]
Ughh, question.

When you have two animations.
Call them
Animation A of a person walking
Animation B of a dog walking

By transition do you mean cross fade transition smoothening
or
keyframe interpolation transition smoothening?
